---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: repo_sync_server
    image: centos:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
